//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Domain_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public File()
        {
            this.AccessRequests = new HashSet<AccessRequest>();
            this.FileVersions = new HashSet<FileVersion>();
            this.AccessUsers = new HashSet<User>();
        }
    
        public int FileID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Title { get; set; }
        public string ShortDesc { get; set; }
        public string AccessLevel { get; set; }
        public int LastVersion { get; set; }
        public string Keywords { get; set; }
        public System.DateTime LastModified { get; set; }
        public string RelativeDirectory { get; set; }
        public string ExternalLink { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccessRequest> AccessRequests { get; set; }
        public virtual User Owner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileVersion> FileVersions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> AccessUsers { get; set; }
    }
}
