//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Domain_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SizeRequest
    {
        public int RequestID { get; set; }
        public int UserID { get; set; }
        public int Amount { get; set; }
        public string Status { get; set; }
        public System.DateTime Stamp { get; set; }
    
        public virtual User User { get; set; }
    }
}
